baseurl = "http://example.org"
title = "The Monties"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "The Monties"
  description = 'Indie Rock - Spokane, Wa'
  logoimage = "images/newM_nobackground.png"
  copyright = "The Monties"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/TheMonties/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/the_monties/"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UCk-Itl_ohKerWBIEoZnaMGw"
