baseurl = "http://example.org"
title = "The Monties"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

<script src="https://use.fontawesome.com/8c943bc553.js"></script>

[params]
  title = "The Monties"
  description = 'Indie Rock - Spokane, Wa'
  logoimage = "images/newM_nobackground.png"
  copyright = "The Monties"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/TheMonties/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/the_monties/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/Sherwoodwt/the_monties_epk"
